### ISSUE TITLE
Appliquer un diviseur au metering

### ISSUE THREAD

**Issue by pierreprinetti** [fairecasoimeme/Zlinky_TIC#286]
Bonjour,

J'ai connecté le Zlinky_TIC en ZHA sur mon Home Assistant (Core v2024.9.3) qui se trouve à moins de deux mètres du capteur. Les données remontent bien, et je reçois certains attributes normalement (par example dans le cluster Basic: app_version `14`, date_code `20240422`, sw_build_id `4000-0014`).

Comme Home Assistant s'attend à recevoir des kWh et le Zlinky_TIC remonte des Wh, je voudrais enregistrer un diviseur de `1000` comme attribute `divisor (id: 0x0302)` dans le cluster `Metering (Endpoint id: 1, Id: 0x0702, Type: in)`.

Cependant: j'entre `1000` dans "Value", je tape "Write attribute", j'ai un joli check blanc sur fond vert, et rien ne se passe. L'enregistrement est toujours en Wh et si je tape "Read attribute", le champ Value prend la valeur `None`.

Est-ce que j'ai mal compris comment enregistrer un diviseur?

**Comment by pierreprinetti** [comment]
En attendant une solution pour régler le problème à la base, voici comment j'ai finalement ajouté un senseur "template" dans ma configuration HomeAsssistant:

```yaml
# dans configuration.yaml

# [...]

template:
  - sensor:
    - name: "Linky"
      unique_id: "lixee_zlinky_tic_summation_delivered_millesime"
      unit_of_measurement: "Wh"
      device_class: energy
      state_class: total_increasing
      state: "{{ states('sensor.lixee_zlinky_tic_summation_delivered') | float }}"
```

J'ai ensuite ajouté ce nouveau senseur virtuel au volet "Energie" pour visualiser ma consommation en électricité.
