### ISSUE TITLE
Firmware version with USB TTL

### ISSUE THREAD

**Issue by sebPomme** [fairecasoimeme/Zlinky_TIC#53]
Salutations, 
J'ai un soucis de version avec ma zigate et homeassistant.
Je suis passé de la version  v2, v3,et maintenant v4 [EDIT et v5 maintenant] (via USB TTL), mais Homeassitant indique : `Firmware: 0x00000001`. 
![zlinky-version](https://user-images.githubusercontent.com/4944971/154556520-e8ae2988-0ca7-4c6e-a66a-dfb8439d5093.png)

Pourtant les cluster 0x0001 & 0x0006 m'indiquent que le firmware est bien à jour.
![zlinky-0x0001](https://user-images.githubusercontent.com/4944971/154556549-b3957ee6-2daa-4410-b5ca-3a98c0cbe3eb.png)

![zlinky-0x0006](https://user-images.githubusercontent.com/4944971/154556595-7173ac88-a1d7-44bc-9805-634c8deb9b2e.png)

Une idée de comment arranger ça ?

Seb

**Comment by pdecat** [comment]
Est-ce que ça aide de lancer une [recherche de mise à jour OTA](https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates#manually-initiating-ota-firmware-update) ?

```
service: zha.issue_zigbee_cluster_command
data:
  ieee: 00:00:00:00:00:00:00:00 # À mettre à jour
  endpoint_id: 1
  cluster_id: 25
  cluster_type: out
  command: 0
  command_type: client
  args:
    - 0
    - 100
```
