### ISSUE TITLE
Problème lecture EAIT à 0

### ISSUE THREAD

**Issue by fairecasoimeme** [fairecasoimeme/Zlinky_TIC#78]
le cluster 0x0702 attribut 0x0001 remonte 0. https://github.com/fairecasoimeme/Zlinky_TIC/issues/73

**Comment by fairecasoimeme** [comment]
Pouvez-vous donnez la valeur STGE cluster 0xff66 attribut 0x217 ?

**Comment by JSteunou** [comment]
J'allais créer un ticket quand j'ai vu votre réponse.

Je ne vois pas de 0x217.

J'ai 0x0300 qui est à 1 (mode standard monophasé)

**Comment by fairecasoimeme** [comment]
Vous ne le voyez pas avec Deconz ? peut-être le rajouter dans le DDF

**Comment by JSteunou** [comment]
Il n'apparait pas non.

![image](https://user-images.githubusercontent.com/2323127/181517161-d9ce8c81-093e-4fd5-9157-8d15dd14a437.png)

Pas sûr que le DDF change quelque chose, c'est plutôt pour mapper des attributs avec l'API REST non ?

**Comment by Smanar** [comment]
Hello, sur un OS classique tu as un fichier XML `/usr/share/deCONZ/zcl/general.xml`
Vers la ligne 3948 tu as le bloc lixee, la ligne a rajouter est cele du millieu

```
        <attribute id="0x0207" type="u16" name="Puissance app. Instantanée injectée" access="r" required="m" default="0x00"/>
        <attribute id="0x0217" type="cstring" name="Registre de Statuts" access="r" required="m"/>
        <attribute id="0x0300" type="u8" name="Protocole Linky" access="r" required="m" default="0x00"/>
```

**Comment by fairecasoimeme** [comment]
Merci @Smanar pour les infos.

**Comment by JSteunou** [comment]
Oui merci, j'ai pu avoir l'info du coup. Ça me dit : `003A0001`

**Comment by fairecasoimeme** [comment]
Ok, la valeur en bit de 003A0001 est :
1110100000000**0**00000001 avec le bit 8 correspondant au fonctionnement de votre linky. Vous pouvez retrouver ces informations sur le doc Enedis-NOI-CPT_54E.pdf (dispo sur le net)

Apparemment, votre Linky est en mode consommateur (même s'il remonte des étiquettes de production).

Je suis en contact avec Enedis qui me dit que c'est une erreur possible. Pour régler le problème, il m'a demandé votre PDL (numéro unique de votre linky) et votre ville. Vous pouvez me les envoyer par mail (contact[at]lixee.fr) et je ferais suivre.

**Comment by gsemet** [comment]
Je pense être dans le même problème, est ce que je peux contacter enedis directement ?

**Comment by JSteunou** [comment]
Ok c'est peut-être *normal* tant que le dossier CAC n'est pas entièrement validé (mais que c'est long...). Mais c'est dommage cette façon de faire car le Linky est capable de comptabiliser l'injection peu importe le mode‚ donc pourquoi ne pas juste transmettre l'info tout le temps ?

**Comment by JSteunou** [comment]
@fairecasoimeme est-ce que ça veut dire que la TIC ne contient pas forcément tout ce qu'on peut lire physiquement sur son linky et que le ZLinky ne peut remonter qu'une partie des informations ?

**Comment by fairecasoimeme** [comment]
@JSteunou 
je communique actuellement avec Enedis, voici un début de réponse sur votre cas : 
```
Le compteur Linky associé au PDL xxxxxxxxxxxxxx est programmé en mode consommateur.

Dans ce mode, comme indiqué dans la note 54E, l'étiquette  EAIT (Energie active injectée totale) n'est pas transmise. Par ailleurs, le client ne dispose pas de contrat avec injection, uniquement soutirage.

Il est nécessaire que les clients aient un compteur configurés en mode producteur. Nous échangerons à le rentrée sur les conditions de basculement en configuration producteur.
```

**Comment by JSteunou** [comment]
Ok donc si je comprends bien, pas de CACSI ou de CRAE pas de mode producteur et pas d EAIT transmise.

Aucun autre moyen de récupérer l'information ? Car côté Linky, je peux le lire, mais c'est juste péniable de faire du relevé manuel plusieurs fois par jour :/

**Comment by JSteunou** [comment]
Et encore même pas sûr pour la CACSI du coup ça se trouve, vous avez l'info ?

**Comment by fairecasoimeme** [comment]
je fais suivre la question

**Comment by gsemet** [comment]
Alors pour ma part, j'ai la valeur toujours à zero et pourtant j'ai bien confirmé avec Enedis que mon compteur est en mode producteur. 
Est-ce que je me serais pas trompé dans mon automatisation pour lire la valeur:
```
automation:
  - alias: Read ZLinky_TIC every minute
    description: ""
    trigger:
      - platform: time_pattern
        hours: "*"
        minutes: /1
        seconds: "0"
    condition: []
    action:
      - service: zha_toolkit.execute
        data:
          command: attr_read
          ieee: 00:15:8d:00:05:d2:a9:c5
          cluster: 1794 # 0x702
          attribute: 0 # 0x0000 : Energie active soutirée totale (Wh)
          state_id: sensor.lixee_zlinky_tic_consumed_metering_forced_refresh
          allow_create: false
      - service: zha_toolkit.execute
        data:
          command: attr_read
          ieee: 00:15:8d:00:05:d2:a9:c5
          cluster: 2820 # 0xB04
          attribute: 1295 # 0x050F # Puissance app. Instantanée soutirée (VA)
          state_id: sensor.lixee_zlinky_tic_consumed_power_forced_refresh
          allow_create: false
      - service: zha_toolkit.execute
        data:
          command: attr_read
          ieee: 00:15:8d:00:05:d2:a9:c5
          cluster: 1794 # 0x702
          attribute: 1 # 0x0001 : Energie active injectée totale (Wh)
          state_id: sensor.lixee_zlinky_tic_injected_metering_forced_refresh
          allow_create: false
      - service: zha_toolkit.execute
        data:
          command: attr_read
          ieee: 00:15:8d:00:05:d2:a9:c5
          cluster: 65382 # 0xFF66
          attribute: 519 # 0x0207 # Puissance app. Instantanée injectée (VA)
          state_id: sensor.lixee_zlinky_tic_injected_power_forced_refresh
          allow_create: false
    mode: single
```

**Comment by fairecasoimeme** [comment]
@gsemet pouvez vous remonter la valeur STGE ? cluster 0xff66 attribut 0x217 ?

**Comment by gsemet** [comment]
Alors avec la commande home assistant:
```
service: zha_toolkit.attr_read
data:
  ieee: 00:15:8d:00:05:d2:a9:c5
  cluster: 65382  # 0xFF66
  attribute: 535  # 0x217
  csvout: zlinky
```

Je lis la valeur suivante:
```
2022-08-04T11:41:49.645837+00:00,Manufacturer Specific,535,b'\x00\x00\x00\x00\x00\x00\x00\x00',0x0217,0xFF66,1,00:15:8d:00:05:d2:a9:c5,
```
